name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Build
        run: |
          mkdir -p dist
          NAME="pihole-toggle-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          go mod download
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$NAME"
          tar -cJf "dist/$NAME.tar.xz" "$NAME"

      - name: Release
        run: |
          if ! gh release view ${{ github.ref_name }} &>/dev/null; then
            gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes --verify-tag
          fi
          gh release upload ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
